codecov:
  require_ci_to_pass: true
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%
        if_ci_failed: error
        only_pulls: true
    patch:
      default:
        target: auto
        threshold: 3% # Allowed drop in coverage for the patch
        if_ci_failed: error
        only_pulls: true
ignore:
  - "examples/**/*"
  - "cmd/risor-api/*"
  - "cmd/risor-docs/*"
  - "cmd/risor-lsp/*"
  - "cmd/risor-modgen/*"
  - "vscode/**/*"
  - "tests/**/*"
  - "terraform/**/*"
  - "research/**/*"
