site_name: Risor
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - go
    - bash
  features:
    - content.code.annotate
  palette:
    scheme: default
    primary: blue
    accent: light-blue
repo_url: https://github.com/risor-io/risor
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - md_in_html
nav:
  - Home: index.md
  - quick-start.md
  - syntax.md
  - built-ins.md
  - data-types.md
  - iterators.md
  - error-handling.md
  - how-it-works.md
  - scripts.md
