# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.22
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v6-{{ checksum "go.sum" }}
      - run:
          name: Show Go Environment
          command: go env
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v6-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            make test
      - codecov/upload
      - store_test_results:
          path: /tmp/test-reports
  generate:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.22
    resource_class: small
    steps:
      - checkout
      # No save_cache, as the "tests" job already does that.
      - restore_cache:
          keys:
            - go-mod-v6-{{ checksum "go.sum" }}
      - run:
          name: Run generate
          command: |
            make generate
            git -c color.ui=always diff --exit-code --stat
  format:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.22
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - gofumpt
      - run:
          name: Install gofumpt
          command: |
            go install mvdan.cc/gofumpt@latest
      - save_cache:
          key: gofumpt
          paths:
            - /home/circleci/go/pkg/mod
      - run:
          name: Run gofumpt
          command: |
            make format
            git -c color.ui=always diff --exit-code --stat
workflows:
  test:
    jobs:
      - test
      - format
      - generate
