# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.21
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v6-{{ checksum "go.sum" }}
      - run:
          name: Show Go Environment
          command: go env
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v6-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
workflows:
  test:
    jobs:
      - test
